name: notebooks-sharing 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab=4.0.2
  - pandas=2.0.2
  - matplotlib=3.7.1
  - joblib=1.2.0
  - seaborn=0.12.2
  - ipywidgets=8.0.6
  - scikit-learn=1.2.2
